// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjetabsxacabnxgbvjat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZXRhYnN4YWNhYm54Z2J2amF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzk4MjYsImV4cCI6MjA2OTcxNTgyNn0.8Kg-ujhKj4RrMxVSnZCDoVF0_rUj3F7XG_jaG1omoj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});